# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    #Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        # Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic`s GitHub Action
        with:
          # Chromatic projectToken
          projectToken: ${{ secrets.980f8be080a1}}
          token: ${{ secrets.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}}
